export const countryMap: { [key: string]: string } = {
    'United States': 'us',
    'Spain': 'es',
    'Switzerland': 'ch',
    'Serbia': 'rs',
    'Great Britain': 'gb',
    'Germany': 'de',
    'Australia': 'au',
    'Russia': 'ru',
    'France': 'fr',
    'Argentina': 'ar',
    'Czech Republic': 'cz',
    'Croatia': 'hr',
    'Italy': 'it',
    'Sweden': 'se',
    'Austria': 'at',
    'Belgium': 'be',
    'Canada': 'ca',
    'Brazil': 'br',
    'Japan': 'jp',
    'South Africa': 'za',
    'Slovakia': 'sk',
    'Netherlands': 'nl',
    'Chile': 'cl',
    'Romania': 'ro',
    'Bulgaria': 'bg',
    'Belarus': 'by',
    'Greece': 'gr',
    'Denmark': 'dk',
    'Ukraine': 'ua',
    'Kazakhstan': 'kz',
    'Hungary': 'hu',
    'Latvia': 'lv',
    'Poland': 'pl',
    'Portugal': 'pt',
    'South Korea': 'kr',
    'Israel': 'il',
    'Finland': 'fi',
    'Norway': 'no',
    'Slovenia': 'si',
    'Uzbekistan': 'uz',
    'Tunisia': 'tn',
    'China': 'cn',
    'India': 'in',
    'Mexico': 'mx',
    'Colombia': 'co',
    'Turkey': 'tr',
    'New Zealand': 'nz',
    'Luxembourg': 'lu',
    'Estonia': 'ee',
    'Thailand': 'th',
    'Georgia': 'ge',
    'Bosnia and Herzegovina': 'ba',
    'Venezuela': 've',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Ecuador': 'ec',
    'Dominican Republic': 'do',
    'Egypt': 'eg',
    'Philippines': 'ph',
    'Moldova': 'md',
    'Lithuania': 'lt',
    'Montenegro': 'me',
    'Armenia': 'am',
    'Cyprus': 'cy',
    'Indonesia': 'id',
    'Malta': 'mt',
    'Vietnam': 'vn',
    'Iceland': 'is',
    'Morocco': 'ma',
    'Lebanon': 'lb',
    'Puerto Rico': 'pr',
    'Monaco': 'mc',
    'Singapore': 'sg',
    'Bolivia': 'bo',
    'Pakistan': 'pk',
    'Algeria': 'dz',
    'Saudi Arabia': 'sa',
    'Qatar': 'qa',
    'Jordan': 'jo',
    'Bangladesh': 'bd',
    'Sri Lanka': 'lk',
    'Malaysia': 'my',
    'United Arab Emirates': 'ae',
    'Kuwait': 'kw',
    'Iraq': 'iq',
    'Bahrain': 'bh',
    'Jamaica': 'jm',
    'Barbados': 'bb',
    'Trinidad and Tobago': 'tt',
    'Costa Rica': 'cr',
    'Honduras': 'hn',
    'El Salvador': 'sv',
    'Uruguay': 'uy',
    'Guatemala': 'gt',
    'Nicaragua': 'ni',
    'Panama': 'pa',
    'Cuba': 'cu',
    'North Macedonia': 'mk',
    'Azerbaijan': 'az',
    'Tajikistan': 'tj',
    'Kyrgyzstan': 'kg'
};
  
  